### ISSUE TITLE
How to change the picture on the top-left corner?

### ISSUE THREAD

**Issue by 0oshowero0** [getgrav/grav-skeleton-lingonberry-site#3]
![image](https://user-images.githubusercontent.com/21094960/37074651-d2073e9c-2208-11e8-8ee8-e7c7e7543371.png)

**Comment by Fastbyte01** [comment]
This is simple, change email address on the voice "gravatar" inside the file site.yaml. The image used here is the image that you have linked with your gravatar account.

**Comment by 0oshowero0** [comment]
I see! Thank you.
